### PR TITLE
fix some config options being ignored and epoch off-by-one error

### PR DESCRIPTION
**Pull request by Sobsz**

### CODE REVIEW

**Comment by sjkoelle** [comment]
Looks good to me.  Want to pull the most recent master and merge.  This should fix the tests failing.

Also, we haven't been maintaining mellotron or vits.  Would it be helpful if we wrote out what the roadmap for the repo is?

**Comment by Sobsz** [comment]
a roadmap would be nice yeah, though really i just put the fixes in there because ¯\_(ツ)_/¯

**Comment by sjkoelle** [comment]
We definitely appreciate it! :)

**Comment by sjkoelle** [comment]
hmmm the tests are still failing.  can you run ./build_lib from the root directory of the repo and repush?  Hopefully that helps.

**Review by sjkoelle — APPROVED** [review]

**Pull request merged**
